name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  init:
    name: Prereqs
    runs-on: ubuntu-24.04
    steps:
      - uses: StyraOSS/styra-init-action@main # ratchet:exclude

  jsr:
    name: Publish @open-policy-agent/opa to JSR
    runs-on: ubuntu-24.04
    needs:
      - release
    if: contains(fromJSON(needs.release.outputs.publishedPackages).*.name, '@open-policy-agent/opa')
    permissions:
      contents: read
      id-token: write # OIDC ID token for authentication with JSR
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
      - name: publish @open-policy-agent/opa to JSR
        run: |
          npm ci
          npx -w packages/opa jsr publish

  release:
    name: Release
    needs: init
    outputs:
      published: ${{ steps.changesets.outputs.published }}
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages  }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write #  to create release (changesets/action)
      actions: write #  to create tags (changesets/action)
      issues: write # to post issue comments (changesets/action)
      pull-requests: write #  to create pull request (changesets/action)
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          npm ci
          npm run build --ws

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@aba318e9165b45b7948c60273e0b72fce0a64eb9 # v1.4.7
        with:
          publish: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  docs:
    name: Publish Docs
    needs:
      - release
    if: needs.release.outputs.published == 'true'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      actions: read
      pages: write
      id-token: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
      - name: Install dependencies
        run: |
          npm ci
          npm run build --ws
      - name: Generate docs
        run: npm run docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          # Upload entire repository
          path: docs/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
